"""uspiflash check: is a committed copy what the installed tools make?"""

from __future__ import annotations

from typing import TYPE_CHECKING

import spiflash

from uspiflash import __version__
from uspiflash.cli import main

if TYPE_CHECKING:
    from pathlib import Path

    import pytest


def test_a_fresh_file_passes(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    out = tmp_path / "uspiflash.h"
    assert main(["generate", "-o", str(out), "--level", "read", "--with", "sfdp"]) == 0
    capsys.readouterr()
    assert main(["check", str(out)]) == 0
    assert capsys.readouterr().out == f"{out}: up to date\n"


def test_an_edited_file_fails_with_versions_and_a_diff(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    out = tmp_path / "uspiflash.h"
    main(["generate", "-o", str(out), "--level", "read"])
    out.write_text(out.read_text().replace("uint8_t usf_lookup(", "uint8_t usf_lookup_edited(", 1))
    capsys.readouterr()
    assert main(["check", str(out)]) == 1
    report = capsys.readouterr().out
    assert report.startswith(f"{out}: out of date\n")
    assert f"generated by uspiflash {__version__}, spiflash {spiflash.__version__}" in report
    assert "-uint8_t usf_lookup_edited(" in report
    assert "+uint8_t usf_lookup(" in report


def test_a_file_without_a_config_is_an_error(tmp_path: Path) -> None:
    other = tmp_path / "other.h"
    other.write_text("/* not generated */\n")
    assert main(["check", str(other)]) == 2


def test_every_file_is_checked(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    good, bad = tmp_path / "a.h", tmp_path / "b.h"
    main(["generate", "-o", str(good), "--level", "id"])
    bad.write_text("/* not generated */\n")
    capsys.readouterr()
    assert main(["check", str(bad), str(good)]) == 2
    assert f"{good}: up to date" in capsys.readouterr().out


def test_a_config_it_cannot_regenerate_is_an_error(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    out = tmp_path / "uspiflash.h"
    main(["generate", "-o", str(out), "--level", "id"])
    out.write_text(out.read_text().replace('"level": "id"', '"level": "nonsense"', 1))
    capsys.readouterr()
    assert main(["check", str(out)]) == 2
    assert "cannot be regenerated" in capsys.readouterr().out
