"""The comment every generated file starts with: what made it, from what,
and how to make it again. It embeds the configuration as one JSON line that
``uspiflash check`` reads back."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from typing import Any

import spiflash
from spiflash.db import FORMAT

from . import __version__
from .levels import LEVELS, Selection

CONFIG_RE = re.compile(r"^ \* uspiflash-config: (\{.*\})$", re.MULTILINE)


@dataclass(frozen=True)
class Config:
    """Everything that determines a generated file's content (with the
    installed uspiflash and spiflash versions)."""

    selection: Selection
    prefix: str = "usf"
    filename: str = "uspiflash.h"

    def to_json(self) -> dict[str, Any]:
        """Plain JSON; key order is fixed so the digest is stable."""
        return {
            "prefix": self.prefix,
            "filename": self.filename,
            "selection": self.selection.to_json(),
        }

    @classmethod
    def from_json(cls, d: dict[str, Any]) -> Config:
        """The inverse of :meth:`to_json`."""
        return cls(Selection.from_json(d["selection"]), d["prefix"], d["filename"])

    def digest(self) -> str:
        """SHA-256 of the canonical JSON."""
        text = json.dumps(self.to_json(), sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(text.encode()).hexdigest()

    def args(self) -> list[str]:
        """The ``uspiflash generate`` arguments that reproduce this config."""
        sel = self.selection
        out = ["-o", self.filename, "--prefix", self.prefix, "--level", sel.level]
        base = LEVELS[sel.level]
        out += [a for f in sorted(sel.fields - base) for a in ("--with", str(f))]
        out += [a for f in sorted(base - sel.fields) for a in ("--without", str(f))]
        c = sel.chips
        out += [a for m in c.manufacturers for a in ("--manufacturer", m)]
        out += [a for i in c.ids for a in ("--id", i.hex())]
        out += [a for t in c.types for a in ("--type", t.value)]
        out += [a for f in c.families for a in ("--family", f.value)]
        if c.min_size is not None:
            out += ["--min-size", str(c.min_size)]
        if c.max_size is not None:
            out += ["--max-size", str(c.max_size)]
        return out


def header(config: Config) -> str:
    """The provenance comment."""
    args = " ".join(_quote(a) for a in config.args())
    src = spiflash.sources()
    lines = [
        f"{config.filename}: detect SPI flash chips and describe them.",
        "",
        f"Generated by uspiflash {__version__} from spiflash {spiflash.__version__}",
        f"(database format {FORMAT}). Do not edit: regenerate it instead.",
        "",
        "The spiflash data was extracted from these upstream commits:",
        *(
            f"  {name} {info.commit} ({info.date:%Y-%m-%d}, {info.license})"
            for name, info in sorted(src.items())
        ),
        "",
        "Regenerate (byte-identical) with:",
        f"  uvx --from 'uspiflash=={__version__}' --with 'spiflash=={spiflash.__version__}' \\",
        f"      uspiflash generate {args}",
        f"Check a committed copy is current with: uspiflash check {config.filename}",
        "",
        f"Configuration (sha256 {config.digest()}):",
        f"uspiflash-config: {json.dumps(config.to_json(), sort_keys=True)}",
        "",
        "Licence: Apache-2.0. The data is from spiflash (Apache-2.0), itself",
        "extracted from the flash tables of Linux, U-Boot, flashrom, flashprog,",
        "OpenOCD, openFPGALoader and QEMU, and Zephyr's board descriptions;",
        "see https://github.com/mithro/spiflash.",
        "",
        "Documentation: https://uspiflash.readthedocs.io/",
    ]
    body = "\n".join(f" * {line}".rstrip() for line in lines)
    if "*/" in body:
        msg = "provenance would end the comment early"
        raise ValueError(msg)
    return f"/*\n{body}\n */\n"


def _quote(arg: str) -> str:
    return arg if re.fullmatch(r"[\w.,:/=+-]+", arg) else "'" + arg.replace("'", "'\\''") + "'"
